Integrate SESOF MagRepack
acemod/ACE-Anvil pull request #51
Opened 2024-04-13 21:12 UTC by kveberg

Adds SESOF MagRepack to ACE Anvil.
- Please somehow note the contributions of Badger 2-3 to this mod -https://github.com/JBraunsmaJr
- This mod presently does not work with consoles because it hooks into drag-and-drop they do not have

2024-04-14 06:14 UTC, Kexanone commented
I updated the folder structure, code style and added ACE prefixes. Make sure to add all contributors to [AUTHORS](https://github.com/acemod/ACE-Anvil/blob/master/AUTHORS). Also it would be good to have a short entry in the [docs](https://github.com/acemod/ACE-Anvil/tree/master/docs/src/components) for the mod with a hint that it originally was `SESOF MagRepack` and that it's not console compatible.

2024-05-24 18:24 UTC, Kexanone commented on addons/magrepack/scripts/Game/ACE_MagRepack/Player/SCR_PlayerController.c
> +		Print("fromMag holds: " + fromCount + " rounds.");
Log level should be set to `DEBUG`. This goes for all subsequent prints that are not error messages.

2024-05-24 18:27 UTC, Kexanone commented on addons/magrepack/scripts/Game/ACE_MagRepack/Player/SCR_PlayerController.c
> +modded class SCR_PlayerController
Parent class missing

2024-05-24 18:27 UTC, Kexanone commented on addons/magrepack/scripts/Game/ACE_MagRepack/UI/Inventory/SCR_InventoryMenuUI.c
> +modded class SCR_InventoryMenuUI
Parent class missing

2024-05-24 18:29 UTC, Kexanone commented on addons/magrepack/scripts/Game/ACE_MagRepack/Player/SCR_PlayerController.c
> +					if (!managerComp.TryRemoveItemFromInventory(toEntity)) {SCR_EntityHelper.DeleteEntityAndChildren(toEntity);}
```suggestion
					if (!managerComp.TryRemoveItemFromInventory(toEntity))
						SCR_EntityHelper.DeleteEntityAndChildren(toEntity);
```

2024-05-24 18:30 UTC, Kexanone commented on addons/magrepack/scripts/Game/ACE_MagRepack/Player/SCR_PlayerController.c
> +					if (!managerComp.TryRemoveItemFromInventory(toEntity)) {SCR_EntityHelper.DeleteEntityAndChildren(toEntity);}
```suggestion
					if (!managerComp.TryRemoveItemFromInventory(toEntity)) 
						SCR_EntityHelper.DeleteEntityAndChildren(toEntity);
```

2024-05-24 18:30 UTC, Kexanone commented on addons/magrepack/scripts/Game/ACE_MagRepack/Player/SCR_PlayerController.c
> +						if (!managerComp.TryRemoveItemFromInventory(fromEntity)) {SCR_EntityHelper.DeleteEntityAndChildren(fromEntity);}
```suggestion
						if (!managerComp.TryRemoveItemFromInventory(fromEntity)) 
							SCR_EntityHelper.DeleteEntityAndChildren(fromEntity);
```

2024-05-24 18:31 UTC, Kexanone commented on addons/magrepack/scripts/Game/ACE_MagRepack/Player/SCR_PlayerController.c
> +			Print("Invalid storageTo", LogLevel.ERROR);
Return statement missing?

2024-05-24 18:31 UTC, Kexanone commented on addons/magrepack/scripts/Game/ACE_MagRepack/Player/SCR_PlayerController.c
> +			Print("Invalid storageFrom", LogLevel.ERROR);
Return statement missing?

2024-05-24 18:37 UTC, Kexanone commented on addons/magrepack/scripts/Game/ACE_MagRepack/UI/Inventory/SCR_InventoryMenuUI.c
> +				ref array<IEntity> items = {};
`ref` is not needed here

2024-05-24 18:41 UTC, Kexanone commented on addons/magrepack/scripts/Game/ACE_MagRepack/UI/Inventory/SCR_InventoryMenuUI.c
> +		protected SCR_PlayerController m_PlayerController = SCR_PlayerController.Cast(GetGame().GetPlayerManager().GetPlayerController(playerId));
```suggestion
		SCR_PlayerController playerController = SCR_PlayerController.Cast(GetGame().GetPlayerController());
```

2024-05-24 18:43 UTC, Kexanone commented on addons/magrepack/scripts/Game/ACE_MagRepack/UI/Inventory/SCR_InventoryMenuUI.c
> +			m_PlayerController.Rpc(m_PlayerController.ACE_MagRepack_RpcAsk_Repack,
Only member variables should have the `m_` prefix.
```suggestion
			playerController.Rpc(playerController.ACE_MagRepack_RpcAsk_Repack, 
```

2024-05-30 19:58 UTC, kveberg commented on addons/magrepack/scripts/Game/ACE_MagRepack/Player/SCR_PlayerController.c
> +modded class SCR_PlayerController
I can add that, of course - it was my impression, however, that this is not the way: https://community.bistudio.com/wiki/Arma_Reforger:Scripting_Modding

2024-05-30 20:11 UTC, Kexanone commented on addons/magrepack/scripts/Game/ACE_MagRepack/Player/SCR_PlayerController.c
> +modded class SCR_PlayerController
I would argue it's more concise to have the base class there. Besides when you create a modded version via a copy of the original, you have it there anyway.

2024-05-30 20:15 UTC, Kexanone commented on addons/magrepack/scripts/Game/ACE_MagRepack/Player/SCR_PlayerController.c
> +modded class SCR_PlayerController
Besides, BI doesn't seem to be clear on which version to use either. Just have a look at the last section about debug process.

2024-05-30 20:46 UTC, kveberg commented on addons/magrepack/scripts/Game/ACE_MagRepack/Player/SCR_PlayerController.c
> +					if (!managerComp.TryRemoveItemFromInventory(toEntity)) {SCR_EntityHelper.DeleteEntityAndChildren(toEntity);}
This is a question of functionality, so it is up to you guys really. TryRemoveItemFromInventory will leave the mag on the ground, and so when you repack you could always pick it up again and fill it with new ammo. I intended to make a drop pouch to go with this but never got around to it (won't likely). Your suggestion there will of course just vanish the entire thing from existence the moment its empty. Which do you prefer for ACE?

2024-05-30 20:54 UTC, kveberg commented on addons/magrepack/scripts/Game/ACE_MagRepack/Player/SCR_PlayerController.c
> +			Print("Invalid storageTo", LogLevel.ERROR);
Apparently, yes. Fixed.

2024-05-30 20:55 UTC, kveberg commented on addons/magrepack/scripts/Game/ACE_MagRepack/UI/Inventory/SCR_InventoryMenuUI.c
> +				ref array<IEntity> items = {};
Right you are!

2024-05-30 20:57 UTC, Kexanone commented on addons/magrepack/scripts/Game/ACE_MagRepack/Player/SCR_PlayerController.c
> +					if (!managerComp.TryRemoveItemFromInventory(toEntity)) {SCR_EntityHelper.DeleteEntityAndChildren(toEntity);}
You misunderstood the suggested change. It's just a matter of how to format a conditional with a body consisting of a single line. There's no change in functionality.
```cs
if (<condition>) { <body>; }
```
vs
```cs
if (<condition>) 
    <body>;
```

2024-06-12 17:57 UTC, kveberg commented on addons/magrepack/scripts/Game/ACE_MagRepack/Player/SCR_PlayerController.c
> +			Print("Invalid storageFrom", LogLevel.ERROR);
Yes, two actually. Fixed.

2024-06-12 17:59 UTC, kveberg commented
I thought I had fixed all these, but apparently had not. Should be good now.

2024-06-12 18:08 UTC, Kexanone requested changes

2024-06-12 18:08 UTC, Kexanone commented on addons/magrepack/scripts/Game/ACE_MagRepack/UI/Inventory/SCR_InventoryMenuUI.c
> +		Print("------- Attempting to repack magazines. -------", LogLevel.NORMAL);
```suggestion
		Print("------- Attempting to repack magazines. -------", LogLevel.DEBUG);
```

2024-06-12 18:15 UTC, Kexanone requested changes

2024-06-12 18:15 UTC, Kexanone commented on addons/magrepack/scripts/Game/ACE_MagRepack/UI/Inventory/SCR_InventoryMenuUI.c
> +			m_PlayerController.ACE_MagRepack_Repack(fromMag, toMag, m_InventoryManager, toItemStorageComponent, fromItemStorageComponent);
```suggestion
			playerController.ACE_MagRepack_Repack(fromMag, toMag, m_InventoryManager, toItemStorageComponent, fromItemStorageComponent);
```

2024-06-13 18:08 UTC, Kexanone requested changes

2024-06-13 18:08 UTC, Kexanone commented on addons/magrepack/scripts/Game/ACE_MagRepack/Player/SCR_PlayerController.c
> +modded class SCR_PlayerController : PlayerControllerClass
```suggestion
modded class SCR_PlayerController : PlayerController
```

2024-06-13 19:10 UTC, Kexanone approved these changes

2024-06-26 08:43 UTC, merged