Ace explosives
acemod/ACE-Anvil pull request #80
Opened 2024-06-28 00:48 UTC by DerivenLoki

- Modifies the Mine.base prefabs MineDamageManager component, rendering gunfire unable to trigger the Trigger component

- Adds the new ACE_Explosives_DeminingUserAction to the Mine.base Prefab to allow the use of a Shovel to disable Landmines

- Modifies the existing ACE_Chopping_UserAction by adding a Parent Class - ACE_ShovelDestroyUserAction, found in ACE Core > Scripts > Game > UserActions - of which Chopping_UserAction now inherits from

2024-06-28 01:11 UTC, Kexanone requested changes

2024-06-28 01:11 UTC, Kexanone commented on addons/explosives/addon.gproj
> + ID "ACEExplosives"
```suggestion
 ID "ACE_Explosives"
```

2024-06-28 01:11 UTC, Kexanone commented on addons/core/scripts/Game/ACE_Core/UserActions/ACE_ShovelDestroyUserAction.c
> +	override bool HasLocalEffectOnlyScript()
Remove this. We only want local effect for chopping.

2024-06-28 01:11 UTC, Kexanone commented on addons/explosives/scripts/Game/ACE_Explosives/Demining/UserActions/ACE_Explosives_DeminingUserAction.c
> +
Remove blank line

2024-12-11 23:09 UTC, veteran29 reviewed
LGTM, I will let Kex approve

2024-12-11 23:25 UTC, Kexanone approved these changes

2024-12-11 23:25 UTC, merged